package network.chapter3.lab5;

import java.math.BigInteger;
import java.security.MessageDigest;
import java.util.Random;
import java.util.Scanner;

import org.apache.commons.codec.digest.DigestUtils;
public class CalcMD5 {
	static String Number="1234567890";
	public static String GetMD5(String str)
	{
		return DigestUtils.md5Hex(str);
	}
	public static void main(String[] args)
	{
		//验证方的口令
		String Key="abc123456efg";
		String RandomNumber="";
		Random Gen=new Random();
		//生成6位随机数
		for(int i=0;i<6;++i)
			RandomNumber+=Number.charAt(Math.abs(Gen.nextInt())%Number.length());
		System.out.print("Please input your password:	");
		Scanner Input=new Scanner(System.in);
		String Password=Input.next();
		String VerMD5=GetMD5(RandomNumber+Password);
		System.out.println();
		//开始验证端
		System.out.println("The password to be verified:	"+Password+"\n");
		System.out.println("The Random Number:		"+RandomNumber+"\n");
		System.out.println("The MD5 to be verified:		"+VerMD5+"\n");
		
		String TrueMD5=GetMD5(RandomNumber+Key);
		System.out.println("The MD5 generated by the Validator:		"+TrueMD5+"\n");
		
		if(TrueMD5.equals(VerMD5))
			System.out.println("Verification Success!\n");
		else System.out.println("Verification Failed!\n");
	}
}
